// Native fetch is available in Node 22

const API = 'http://localhost:5000'

function id(prefix = '') {
  return prefix + Date.now().toString(36) + Math.random().toString(36).slice(2)
}

const now = new Date().toISOString()
const in1Day = new Date(Date.now() + 86400 * 1000).toISOString()
const in2Days = new Date(Date.now() + 2 * 86400 * 1000).toISOString()

const deals = [
  {
    slug: 'iphone-15-pro-max-amazon',
    title: 'Apple iPhone 15 Pro Max (256GB)',
    store: 'Amazon',
    category: 'Electronics',
    discountLabel: 'Save ₹15,000',
    discountValue: 10,
    type: 'deal',
    price: '₹1,44,900',
    priceValue: 144900,
    usageCount: '15.2k',
    expiresInSeconds: 86400 * 3,
    successRate: 98,
    expiry: 'Expires on 15 Apr',
    badge: 'HOT',
    code: '',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    description: 'Get the incredibly powerful iPhone 15 Pro Max. Features Titanium design, A17 Pro chip, and much more at a massive discount.',
    terms: 'Valid on specific credit cards (HDFC/SBI). Stock subject to availability.',
    steps: ['Visit Amazon', 'Select iPhone 15 Pro Max', 'Apply HDFC Card at checkout for instant discount', 'Complete purchase'],
    highlights: ['A17 Pro chip', 'Titanium build', 'Action button', '5x Optical Zoom'],
    createdAt: now,
  },
  {
    slug: 'sony-wh-1000xm5-croma',
    title: 'Sony WH-1000XM5 Noise Cancelling',
    store: 'Croma',
    category: 'Electronics',
    discountLabel: 'Save 30%',
    discountValue: 30,
    type: 'deal',
    price: '₹22,990',
    priceValue: 22990,
    usageCount: '8.4k',
    expiresInSeconds: 86400 * 5,
    successRate: 95,
    expiry: 'Expires on 20 Apr',
    badge: 'TRENDING',
    code: 'SONY30',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80',
    description: 'Industry leading noise cancellation over-ear headphones from Sony. Crystal clear audio with 30 hours of battery life.',
    terms: 'Use coupon SONY30 to get an extra 5% off over the 25% discount.',
    steps: ['Visit Croma website', 'Add to cart', 'Apply SONY30 promo code', 'Checkout via UPI for extra cashback'],
    highlights: ['Auto NC Optimizer', 'Up to 30Hr Battery', 'Ultra-comfortable', 'Multi-point connection'],
    createdAt: now,
  },
  {
    slug: 'nike-air-max-myntra',
    title: 'Nike Air Max 90 Sneakers',
    store: 'Myntra',
    category: 'Fashion',
    discountLabel: 'Save 40%',
    discountValue: 40,
    type: 'deal',
    price: '₹5,995',
    priceValue: 5995,
    usageCount: '12k',
    expiresInSeconds: 86400 * 2,
    successRate: 90,
    expiry: 'Expires in 48h',
    badge: 'FLASH',
    code: 'AIRMAX40',
    image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&w=800&q=80',
    description: 'Classic Nike Air Max sneakers on Myntra End of Reason Sale. Grab them before sizes run out!',
    terms: 'Valid on select sizes only. Return policy: 14 days.',
    steps: ['Go to Myntra Nike Section', 'Pick your size', 'Apply code AIRMAX40', 'Pay'],
    highlights: ['Iconic Waffle outsole', 'Max Air cushioning', 'Premium leather accents'],
    createdAt: now,
  },
  {
    slug: 'samsung-galaxy-s24-ultra',
    title: 'Samsung Galaxy S24 Ultra',
    store: 'Samsung',
    category: 'Smartphones',
    discountLabel: 'Get Galaxy Watch6 Free',
    discountValue: 25,
    type: 'deal',
    price: '₹1,29,999',
    priceValue: 129999,
    usageCount: '5.6k',
    expiresInSeconds: 86400 * 10,
    successRate: 98,
    expiry: 'Expires end of month',
    badge: 'EXCLUSIVE',
    code: '',
    image: 'https://images.unsplash.com/photo-1706606991142-6e2bb7db287e?auto=format&fit=crop&w=800&q=80',
    description: 'Buy a Samsung Galaxy S24 Ultra and get a Galaxy Watch6 practically free in cart.',
    terms: 'Must add both items to cart. Valid only on Samsung Official App.',
    steps: ['Open Samsung App', 'Add S24 Ultra to cart', 'Add Watch6 to cart', 'Watch6 price drops to zero'],
    highlights: ['Snapdragon 8 Gen 3 for Galaxy', 'AI features', 'S-Pen included', '200MP Main Camera'],
    createdAt: now,
  },
  {
    slug: 'dominos-bogo-pizza',
    title: "Domino's Buy 1 Get 1 Free",
    store: 'Dominos',
    category: 'Food',
    discountLabel: 'BOGO',
    discountValue: 50,
    type: 'coupon',
    price: 'Buy 1 Get 1',
    priceValue: 0,
    usageCount: '45k',
    expiresInSeconds: 3600 * 24,
    successRate: 99,
    expiry: 'Expires Tonight',
    badge: 'HOT',
    code: 'BOGO50',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    description: 'Get any medium or large pizza free when you buy one. Applicable on all crusts except cheese burst.',
    terms: 'Valid on App orders only. Not applicable on combo offers.',
    steps: ['Open Pizza App', 'Add 2 Pizzas', 'Use code BOGO50', 'Lower priced pizza becomes free'],
    highlights: ['Valid across India', 'Max discount ₹500', 'Delivery within 30 mins'],
    createdAt: now,
  },
  {
    slug: 'macbook-air-m2-flipkart',
    title: 'Apple MacBook Air M2 (256GB)',
    store: 'Flipkart',
    category: 'Laptops',
    discountLabel: 'Save ₹20,000',
    discountValue: 20,
    type: 'deal',
    price: '₹79,990',
    priceValue: 79990,
    usageCount: '18k',
    expiresInSeconds: 86400 * 4,
    successRate: 96,
    expiry: 'Expires in 4 days',
    badge: 'TRENDING',
    code: '',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    description: 'The ultra-portable M2 MacBook Air at its lowest price ever on Flipkart. Includes instant bank discount.',
    terms: 'Must use ICICI/Axis Bank Credit Cards for maximum discount.',
    steps: ['Open Flipkart', 'Search MacBook Air M2', 'Select valid Credit Card', 'Discount automatically applies'],
    highlights: ['M2 Chip', 'up to 18 hours battery', 'Liquid Retina display', 'MagSafe charging'],
    createdAt: now,
  },
  {
    slug: 'make-my-trip-goa-flight',
    title: 'MakeMyTrip: Flat ₹1500 Off on Flights',
    store: 'MakeMyTrip',
    category: 'Travel',
    discountLabel: 'Flat ₹1500 OFF',
    discountValue: 15,
    type: 'coupon',
    price: 'Starting ₹3,499',
    priceValue: 3499,
    usageCount: '9.2k',
    expiresInSeconds: 86400 * 7,
    successRate: 85,
    expiry: 'Expires in 7 days',
    badge: 'TRAVEL',
    code: 'FLY1500',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80',
    description: 'Get Flat ₹1500 off on any domestic round-trip flight booking via MakeMyTrip.',
    terms: 'Minimum booking value ₹6,000. Valid once per user.',
    steps: ['Select Flights', 'Proceed to Checkout', 'Apply FLY1500', 'Pay with any mode'],
    highlights: ['Zero Cancellation options', 'Valid on all domestic routes'],
    createdAt: now,
  },
  {
    slug: 'adidas-ultraboost-ajio',
    title: 'Adidas UltraBoost Running Shoes',
    store: 'Ajio',
    category: 'Fashion',
    discountLabel: 'Min 50% OFF',
    discountValue: 50,
    type: 'deal',
    price: '₹8,999',
    priceValue: 8999,
    usageCount: '6.4k',
    expiresInSeconds: 86400,
    successRate: 91,
    expiry: 'Expires Tomorrow',
    badge: 'LIMITED',
    code: '',
    image: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80',
    description: 'Ultimate running comfort with Adidas UltraBoost, now at half price on Ajio.',
    terms: 'Pre-paid orders only. Not eligible for return unless defective.',
    steps: ['Visit Ajio', 'Add to Cart', 'Pay via UPI/Card'],
    highlights: ['Boost midsole', 'Primeknit upper', 'Continental Rubber outsole'],
    createdAt: now,
  },
  {
    slug: 'lg-55-oled-tv',
    title: 'LG 55" OLED 4K Smart TV',
    store: 'Reliance Digital',
    category: 'Electronics',
    discountLabel: 'Save 45%',
    discountValue: 45,
    type: 'deal',
    price: '₹89,990',
    priceValue: 89990,
    usageCount: '2.1k',
    expiresInSeconds: 86400 * 15,
    successRate: 97,
    expiry: 'Expires on 30 Apr',
    badge: 'HOT',
    code: 'OLED10',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    description: 'Experience true black and vivid colors with the LG 55 inch OLED TV. Additional 10% discount with code.',
    terms: 'Free Installation. 1 Year comprehensive warranty.',
    steps: ['Visit Reliance Digital', 'Apply Code OLED10', 'Select Delivery Slot', 'Pay'],
    highlights: ['Self-lit OLED pixels', 'α9 Gen5 AI Processor', 'Dolby Vision IQ & Atmos', '120Hz Refresh Rate'],
    createdAt: now,
  },
  {
    slug: 'swiggy-instamart-50-off',
    title: 'Swiggy Instamart 50% OFF Groceries',
    store: 'Swiggy',
    category: 'Groceries',
    discountLabel: '50% OFF',
    discountValue: 50,
    type: 'coupon',
    price: 'Max discount ₹100',
    priceValue: 0,
    usageCount: '120k',
    expiresInSeconds: 43200,
    successRate: 99,
    expiry: 'Expires Tonight',
    badge: 'NEW',
    code: 'INSTA50',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    description: 'Get your groceries delivered in 10 mins with flat 50% off on your first Swiggy Instamart order.',
    terms: 'Valid for new users or users ordering after 3 months.',
    steps: ['Open Swiggy App', 'Go to Instamart', 'Add items worth ₹200+', 'Apply INSTA50'],
    highlights: ['10 minute delivery', 'Fresh products', 'No delivery fee'],
    createdAt: now,
  }
];

const lootDeals = [
  {
    slug: 'boat-airdopes-141-loot',
    title: 'boAt Airdopes 141 – Massive 80% OFF',
    category: 'Electronics',
    discountPercent: 80,
    oldPrice: '₹4,490',
    newPrice: '₹899',
    grabbed: '25k+',
    stockLabel: 'Selling extremely fast!',
    urgency: 'Sale ends in 2 hours!',
    expiresInSeconds: 7200,
    popularity: 98,
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80',
    description: 'Mindblowing deal on boAt Airdopes 141. Get them for just ₹899 instead of ₹4490. Stock vanishing rapidly!',
    steps: ['Click the Grab Deal button instantly', 'It takes you to Flipkart', 'Add to cart & checkout immediately'],
    terms: 'Max 1 unit per customer. COD might not be available.',
    link: 'https://flipkart.com'
  },
  {
    slug: 'puma-tshirt-299',
    title: 'Puma Men Graphic T-Shirt Loot',
    category: 'Fashion',
    discountPercent: 75,
    oldPrice: '₹1,299',
    newPrice: '₹299',
    grabbed: '14k+',
    stockLabel: 'Only L and XL remaining',
    urgency: 'Sizes selling out!',
    expiresInSeconds: 10800,
    popularity: 95,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
    description: 'Grab a branded Puma graphic tee for the price of a local one! Unbelievable discount on Myntra right now.',
    steps: ['Click Grab Deal', 'Filter by your size', 'Apply direct discount'],
    terms: 'Non-returnable item. Limit 5 per user.',
    link: 'https://myntra.com'
  },
  {
    slug: 'sandisk-128gb-pendrive',
    title: 'SanDisk 128GB Cruzer Blade Pen Drive',
    category: 'Computer Accessories',
    discountPercent: 65,
    oldPrice: '₹1,500',
    newPrice: '₹349',
    grabbed: '8k+',
    stockLabel: 'Out of stock soon',
    urgency: 'Flash Deal - Ends in 1 Hour!',
    expiresInSeconds: 3600,
    popularity: 92,
    image: 'https://images.unsplash.com/photo-1615467472314-e56c547fb07e?auto=format&fit=crop&w=800&q=80',
    description: 'Super cheap 128GB flash drive. Backup all your photos and videos reliably for just ₹349.',
    steps: ['Visit Amazon', 'Apply ₹150 clipping coupon on page', 'Checkout'],
    terms: 'Sold by Appario Retail. 5-year warranty.',
    link: 'https://amazon.in'
  },
  {
    slug: 'noise-colorfit-smartwatch',
    title: 'Noise ColorFit Pulse Smartwatch',
    category: 'Electronics',
    discountPercent: 80,
    oldPrice: '₹4,999',
    newPrice: '₹999',
    grabbed: '42k+',
    stockLabel: 'Only Black color left',
    urgency: 'Hot Loot 🔥🔥',
    expiresInSeconds: 14400,
    popularity: 99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    description: 'Lowest price ever tracked for the Noise ColorFit smartwatch featuring SPO2 and heart rate monitor.',
    steps: ['Tap Grab Deal', 'Buy directly from Official Website'],
    terms: 'Prepaid orders get extra 5% off.',
    link: 'https://gonoise.com'
  },
  {
    slug: 'nivea-men-face-wash-99',
    title: 'Nivea Men Face Wash (100g) Loot',
    category: 'Beauty & Grooming',
    discountPercent: 50,
    oldPrice: '₹199',
    newPrice: '₹99',
    grabbed: '11k+',
    stockLabel: 'Always active',
    urgency: 'Daily Deals',
    expiresInSeconds: 43200,
    popularity: 85,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80',
    description: 'Stock up your grooming kit with this 50% flat discount on Nivea Face washes on Amazon Fresh.',
    steps: ['Add 3+ units for free shipping'],
    terms: 'Only for Amazon Prime users',
    link: 'https://amazon.in'
  },
  {
    slug: 'milton-thermosteel-flask-499',
    title: 'Milton Thermosteel 1L Flask',
    category: 'Home & Kitchen',
    discountPercent: 60,
    oldPrice: '₹1,250',
    newPrice: '₹499',
    grabbed: '6.5k+',
    stockLabel: 'Restocked!',
    urgency: 'Valid till midnight',
    expiresInSeconds: 28800,
    popularity: 88,
    image: 'https://images.unsplash.com/photo-1606118942080-60fcf5225d76?auto=format&fit=crop&w=800&q=80',
    description: 'Keep water hot or cold for 24 hours. The legendary Milton Thermosteel flask at its lowest price.',
    steps: ['Find deal on Flipkart', 'Claim SuperCoin offer'],
    terms: 'Need 50 SuperCoins to claim ₹499 price.',
    link: 'https://flipkart.com'
  },
  {
    slug: 'levis-jeans-85-off',
    title: "Levi's Men 511 Slim Fit Jeans",
    category: 'Fashion',
    discountPercent: 85,
    oldPrice: '₹3,599',
    newPrice: '₹539',
    grabbed: '18k+',
    stockLabel: 'Very few sizes',
    urgency: 'Ending in 30 mins!',
    expiresInSeconds: 1800,
    popularity: 100,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=80',
    description: 'Insane clearance sale on Levi\'s on Myntra. Literal daylight robbery at this price point.',
    steps: ['Click quickly', 'Check if your size is available', 'Buy instantly'],
    terms: 'No returns allowed on clearance sale items.',
    link: 'https://myntra.com'
  },
  {
    slug: 'jbl-go-2-bluetooth',
    title: 'JBL GO 2 Bluetooth Speaker',
    category: 'Electronics',
    discountPercent: 70,
    oldPrice: '₹2,999',
    newPrice: '₹899',
    grabbed: '35k+',
    stockLabel: 'Over 1000 left',
    urgency: 'Trending Loot Deals',
    expiresInSeconds: 86400,
    popularity: 97,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    description: 'Waterproof portable speaker with JBL Signature Sound. Perfect for showers and small rooms.',
    steps: ['Available on Reliance Digital'],
    terms: 'Select store pickup for free shipping.',
    link: 'https://reliancedigital.in'
  },
  {
    slug: 'lipton-green-tea-149',
    title: 'Lipton Honey Lemon Green Tea (100 Bags)',
    category: 'Groceries',
    discountPercent: 65,
    oldPrice: '₹450',
    newPrice: '₹149',
    grabbed: '5k+',
    stockLabel: 'Plenty available',
    urgency: 'Good for Health & Wallet',
    expiresInSeconds: 172800,
    popularity: 82,
    image: 'https://images.unsplash.com/photo-1576092762791-dd9e2220cad1?auto=format&fit=crop&w=800&q=80',
    description: 'Immunity boosting Lipton Green tea mega pack. Incredible steal for your morning routine.',
    steps: ['Use code LIPTON at BigBasket checkout'],
    terms: 'Requires ₹500 min order on BigBasket.',
    link: 'https://bigbasket.com'
  },
  {
    slug: 'wildcraft-30l-backpack',
    title: 'Wildcraft 30L Laptop Backpack',
    category: 'Fashion',
    discountPercent: 75,
    oldPrice: '₹3,199',
    newPrice: '₹799',
    grabbed: '16k+',
    stockLabel: 'Selling out fast',
    urgency: 'Only Grey & Black left',
    expiresInSeconds: 36000,
    popularity: 93,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    description: 'Premium Wildcraft laptop backpack with waterproof material. Best loot deal of the week on Myntra!',
    steps: ['Visit Myntra instantly', 'Select color', 'Checkout'],
    terms: 'Free delivery for Myntra Insiders.',
    link: 'https://myntra.com'
  }
];

async function seed() {
  try {
    for (const deal of deals) {
       console.log("Seeding deal:", deal.title)
       await fetch(API + '/api/deals', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify(deal)
       })
    }
    
    for (const loot of lootDeals) {
       console.log("Seeding loot deal:", loot.title)
       loot.id = id('ld')
       await fetch(API + '/api/lootDeals', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify(loot)
       })
    }
    
    console.log('✅ Successfully seeded 10 Deals and 10 Loot Deals into the Database!')
  } catch (error) {
    console.error('Error seeding data:', error)
  }
}

seed();
